<template>
    <HeaderComponent></HeaderComponent>
    <UstmenuComponent></UstmenuComponent>
    <CarouselComponent></CarouselComponent>
    <UstbannerComponent></UstbannerComponent>
    <KayanUrunComponent></KayanUrunComponent>
    <ListtabComponent></ListtabComponent>
    <AltbannerComponent></AltbannerComponent>
    <FooterComponent></FooterComponent>
</template>